<!DOCTYPE html>
<html>
<head>
	<title>МЗКІТ Лабораторна робота № 15</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="style.css">

</head>
<body>
	<div id="head">
		<div  class="paper">
		<div id="colontitle">МЗКІТ Лабораторна робота № 15</div>
		<ul class="lec-menu"> 
			<li><a href="index.html">Зміст</a></li> 
			<li><a href="lab-01.html">01</a></li> 
			<li><a href="lab-02.html">02</a></li> 
			<li><a href="lab-03.html">03</a></li> 
			<li><a href="lab-04.html">04</a></li> 
			<li><a href="lab-05.html">05</a></li> 
			<li><a href="lab-06.html">06</a></li> 
			<li><a href="lab-07.html">07</a></li> 
			<li><a href="lab-08.html">08</a></li> 
			<li><a href="lab-09.html">09</a></li> 
			<li><a href="lab-10.html">10</a></li>  
			<li><a href="lab-11.html">11</a></li> 
			<li><a href="lab-12.html">12</a></li> 
			<li><a href="lab-13.html">13</a></li> 
			<li><a href="lab-14.html">14</a></li> 
			<li><a href="lab-15.html">15</a></li> 
			<li><a href="lab-16.html">16</a></li> 
			<li><a href="lab-17.html">17</a></li> 
			<li><a href="lab-18.html">18</a></li> 
			<li><a href="lab-19.html">19</a></li> 
			<li><a href="lab-20.html">20</a></li>  
		</ul>  
	</div>
	</div>

	<div id="content" class="paper">
		<h1>Обробка помилок обчислень</h1>
		<h2>Мета роботи</h2>
		<p>Розглянути можливості обробки помилок в JavaScript. Навчитись оброблювати реальні помилки, що можуть призводити до неправильної роботи коду сторінки.</p>
		<h2>Обладнання</h2>
		<p>Персональний комп'ютер. Текстовий редактор Sublime Text 3 або Notepad++. Пакет програм XAMPP. Web-браузер Chrome, Firefox, Opera, MS Edge</p>
		<h2>Теоретичні відомості</h2>
		<h3>Обробка помилок, "try..catch"</h3>
		<p>
			Неважливо, наскільки ми хороші в програмуванні, іноді наші скрипти містять помилки. Вони можуть виникати через наших промахів, несподіваного введення користувача, неправильної відповіді сервера і по тисячі інших причин.
		</p>
		<p>
			Зазвичай скрипт в разі помилки «падає» (відразу ж зупиняється), з виведенням помилки в консоль.
		</p>
		<p>
			Але є синтаксична конструкція try..catch, яка дозволяє «ловити» помилки і замість падіння робити щось більш осмислене.
		</p>

		<h3>Синтаксис «try…catch»</h3>
		<p>
			Конструкція try..catch складається з двох основних блоків: try, і потім catch:
		</p>
		<pre>
try 
{
	// код...
} 
catch (err) 
{
	// оброка помилок
}
		</pre>
		<p>
			Працює вона так:
		</p>
		<p>
			Спочатку виконується код всередині блоку try {...}.
            Якщо в ньому немає помилок, то блок catch (err) ігнорується: виконання доходить до кінця try і потім далі, повністю пропускаючи catch.
		</p>
		<p>
			Якщо ж в ньому виникає помилка, то виконання try переривається, і потік управління переходить в початок catch (err). Мінлива err (можна використовувати будь-яке ім'я) містить об'єкт помилки з докладною інформацією про те, що сталося.
		</p>
		<figure>
			<img class="figc" src="img/try-catch-flow.svg">
			<figcaption>Приблизний вигляд меню</figcaption>
		</figure>
		<p>
			Таким чином, при помилці в блоці try {...} скрипт не "падає", і ми отримуємо можливість обробити помилку всередині catch.
		</p>

		<pre>
try 
{
	alert('Початок блоку try');  // (1) <--
	lalala; // помилка, змінна не визначена!
	alert('Кінець блоку try (ніколи не виконається)');  // (2)
} 
catch(err) 
{
	alert(`Виникла помилка!`); // (3) <--
}
		</pre>
		<p class="notice">
			try..catch працює тільки для помилок, що виникають під час виконання коду. Щоб try..catch працював, код повинен бути здійсненним. Він не спрацює, якщо код синтаксично невірний, наприклад, містить не співпадає кількість фігурних дужок або інші помилки.
		</p>

		<p>
			try..catch працює синхронно: виключення, яке відбудеться в коді, запланованому «на майбутнє», наприклад в setTimeout, try..catch не зловить.
		</p>
		<h3>Об'єкт помилки</h3>
		<p>
			Коли виникає помилка, JavaScript генерує об'єкт, що містить її деталі. Потім цей об'єкт передається як аргумент в блок catch:
		</p>
		<pre>
try 
{
	// ...
} 
catch(err) 
{ // <-- об'єкт помилки, можна використовувати іншу назву замість err
	// ...
}
		</pre>
		<p>
			Для всіх вбудованих помилок цей об'єкт має дві основні властивості:
		</p>
		<ul>
			<Li> name - Ім'я помилки. Наприклад, для невизначеної змінної це "ReferenceError". </Li>
            <Li> message - Текстове повідомлення про деталі помилки. </Li>
            <Li> stack - Поточний стек виклику: рядок, що містить інформацію про послідовність вкладених викликів, які призвели до помилки. Використовується з метою налагодження. </Li>
           </ul>

		<h2>Хід роботи</h2>	
		<ol>
			<li>Перевірити чи встановлено пакет програм web-розробника XAMPP</li>
			<li>Викликати панель керування xampp-control.exe</li>
			<li>Впевнитись, що web-сервер Apache запущений</li>
			<li>Перейти за адресою <code>http://127.0.0.1/</code> або <code>http://localhost/</code> та впевнитись, що сторінка вітання XAMPP завантажилась</li>
			<li>Очистити зміст каталогу <code>C:\xampp\htdocs\</code></li>
			<li>Створити файл <code>index.html</code> в середині каталогу <code>C:\xampp\htdocs\</code></li>
			<li>Перейти за адресою <code>http://127.0.0.1/</code> або <code>http://localhost/</code> та впевнитись, що сторінка, яку ви створили, завантажилася корректно</li>
			<li>Створити файл з назвою <code>script.js</code> та помістити його поряд з файлом <code>index.html</code></li>
			<li>Підключити файл <code>script.js</code> в секції <code>&lt;head&gt;</code></li>
			<li>За допомогою оператору <code>throw</code> згенерувати помилку та вивести повідомлення в консоль браузеру</li>
			<li>За допомогою оператору <code>throw</code> згенерувати помилку та вивести повідомлення за допомогою функції <code>alert();</code></li>
			<li>За допомогою оператору <code>throw</code> згенерувати помилку та вивести повідомлення у спливаючому вікні з поясненням помилки. Вікно реалізувати за допомогою прихованого блоку <code>&lt;div&gt;</code> керування вікном має бути реалізоване за допомогою JavaScript</li>
			<li>Імітувати помилку звернення до елементу сторінки якого не існує. Повідомлення про помилку реалізувати як у попередньому пункті</li>
			<li>Імітувати помилку виклику функції, якої не вснує. Повідомлення про помилку реалізувати як у попередньому пункті</li>
			<li>Код JavaScript розмістити у файлі <code>script.js</code> почергово та перевірити його роботу</li>
			<li>У "підвал" сторінки та файл <code>script.js</code> помістити інформацію про виконавця роботи: група, ПІБ, дата виконання.</li>
			<li>Для кожного етапу роботи зробити знімки екрану або скопіювати текст консолі та додати їх у звіт з описом кожного скіншота</li>
			<li>Зберегти звіт у форматі PDF</li>
			<li>Роздрукувати звіт та письмово відповісти на контрольні запитання</li>
		</ol>
		<h2>Контрольні питання</h2>
		<ol>
			<li>Для чого потрібні оператори  "try..catch"?</li>
			<li>Яка послідовність роботи операторів в середині секцій "try", "catch" та "finaly"?</li>
			<li>Які види помилок можна обробити за допомогою  "try..catch"?</li>
			<li>Яким чином штучно імітувати помилку?</li>

		</ol>
		<h2>Довідники та додаткові матеріали</h2>
		<ol>
			<li id="link01"><a href="https://validator.w3.org/">Валідатор W3C</a></li>
			<li id="link02"><a href="https://learn.javascript.ru/">Современный учебник JavaScript</a></li>
			<li id="link03"><a href="http://htmlbook.ru/">Справочник по HTML</a></li>
			<li id="link04"><a href="https://learn.javascript.ru/try-catch">Обработка ошибок, "try..catch"</a></li>
			<li id="link05"><a href="https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Control_flow_and_error_handling">Порядок выполнения и обработка ошибок</a></li>
			<li id="link06"><a href="https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/throw">Инструкция throw</a></li>
		</ol>	
	</div>
</body>
</html>